theme: jekyll-theme-cayman
title: UICircularProgressRing
description: A circular progress bar for iOS written in Swift
show_downloads: true
pods_url: https://cocoapods.org/pods/UICircularProgressRing
release_url: https://github.com/luispadron/UICircularProgressRing/releases
docs_url: https://htmlpreview.github.io/?https://raw.githubusercontent.com/luispadron/UICircularProgressRing/master/docs/Classes/UICircularProgressRingView.html
